# Generated by Django 6.0.8 on 2026-08-22 17:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("discoverable", "Discoverable"),
                            ("restricted", "Restricted"),
                        ],
                        db_index=True,
                        default="restricted",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="libraries",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "library",
                "verbose_name_plural": "libraries",
                "db_table": "libraries_library",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LibraryAccessPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("administrator", "Administrator"),
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                        ],
                        db_index=True,
                        default="student",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_policies",
                        to="libraries.library",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_access_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "library access policy",
                "verbose_name_plural": "library access policies",
                "db_table": "libraries_accesspolicy",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="library",
            constraint=models.UniqueConstraint(
                fields=("institution", "slug"),
                name="libraries_library_institution_slug_unique",
                violation_error_message="A library with this slug already exists in this institution.",
            ),
        ),
        migrations.AddConstraint(
            model_name="libraryaccesspolicy",
            constraint=models.UniqueConstraint(
                fields=("library", "user"),
                name="libraries_accesspolicy_user_library_unique",
                violation_error_message="This user already has an access policy for this library.",
            ),
        ),
    ]
