# Generated by Django on 2026-08-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Add scope_type with default 'institution' so existing records are institutional
        migrations.AddField(
            model_name="library",
            name="scope_type",
            field=models.CharField(
                choices=[("personal", "Personal"), ("institution", "Institution")],
                db_index=True,
                default="institution",
                max_length=20,
            ),
        ),
        # 2. Make institution nullable
        migrations.AlterField(
            model_name="library",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="libraries",
                to="institutions.institution",
            ),
        ),
        # 3. Add owner FK for personal libraries
        migrations.AddField(
            model_name="library",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_libraries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # 4. Remove old unconditioned unique constraint
        migrations.RemoveConstraint(
            model_name="library",
            name="libraries_library_institution_slug_unique",
        ),
        # 5. Add ownership check constraint
        migrations.AddConstraint(
            model_name="library",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        scope_type="personal",
                        owner__isnull=False,
                        institution__isnull=True,
                    )
                    | models.Q(
                        scope_type="institution",
                        institution__isnull=False,
                        owner__isnull=True,
                    )
                ),
                name="libraries_library_ownership_valid",
                violation_error_message=(
                    "A personal library must have an owner and no institution; "
                    "an institutional library must have an institution and no owner."
                ),
            ),
        ),
        # 6. Add conditional unique constraints
        migrations.AddConstraint(
            model_name="library",
            constraint=models.UniqueConstraint(
                condition=models.Q(scope_type="institution"),
                fields=["institution", "slug"],
                name="libraries_library_institution_slug_unique",
                violation_error_message=(
                    "A library with this slug already exists in this institution."
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="library",
            constraint=models.UniqueConstraint(
                condition=models.Q(scope_type="personal"),
                fields=["owner", "slug"],
                name="libraries_library_owner_slug_unique",
                violation_error_message=(
                    "You already have a personal library with this slug."
                ),
            ),
        ),
        # 7. Add indexes
        migrations.AddIndex(
            model_name="library",
            index=models.Index(
                fields=["owner", "-created_at"],
                name="lib_owner_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="library",
            index=models.Index(
                fields=["institution", "-created_at"],
                name="lib_inst_created_idx",
            ),
        ),
        # 8. Set model default for scope_type to 'personal' for subsequent model instantiation
        migrations.AlterField(
            model_name="library",
            name="scope_type",
            field=models.CharField(
                choices=[("personal", "Personal"), ("institution", "Institution")],
                db_index=True,
                default="personal",
                max_length=20,
            ),
        ),
    ]
