# Generated by Django 6.0.8 on 2026-09-04 16:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0004_institution_logo_content_type_and_more"),
        ("libraries", "0002_library_personal_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient_email", models.EmailField(db_index=True, max_length=254)),
                (
                    "intended_access",
                    models.CharField(
                        choices=[
                            ("administrator", "Administrator"),
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                        ],
                        db_index=True,
                        default="student",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Cryptographically secure single-use token for resolving the invitation.",
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_invitations",
                        to="institutions.institution",
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_library_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="libraries.library",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_library_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "library invitation",
                "verbose_name_plural": "library invitations",
                "db_table": "libraries_libraryinvitation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["library", "status"],
                        name="libraries_l_library_2980d8_idx",
                    ),
                    models.Index(
                        fields=["recipient_email", "status"],
                        name="libraries_l_recipie_4d4dfc_idx",
                    ),
                    models.Index(fields=["token"], name="libraries_l_token_81fd01_idx"),
                    models.Index(
                        fields=["expires_at"], name="libraries_l_expires_a91277_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("library", "recipient_email"),
                        name="libraries_invitation_unique_pending",
                        violation_error_message="A pending invitation already exists for this email address.",
                    )
                ],
            },
        ),
    ]
