# Generated by Django 6.0.8 on 2026-09-04 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0005_alter_institutionalauditevent_action_academicunit"),
        ("libraries", "0003_libraryinvitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="academic_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Academic unit targeted by this library when target_type is academic_unit.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="targeted_libraries",
                to="institutions.academicunit",
            ),
        ),
        migrations.AddField(
            model_name="library",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("utility", "Universal Utility"),
                    ("academic_unit", "Academic Unit Shelf"),
                ],
                db_index=True,
                default="utility",
                help_text="Targeting scope of this library (utility for all or targeted to an academic unit).",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="library",
            index=models.Index(
                fields=["institution", "target_type"], name="lib_inst_target_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="library",
            index=models.Index(
                fields=["academic_unit", "-created_at"], name="lib_acad_unit_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="library",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("academic_unit__isnull", True), ("target_type", "utility")
                    ),
                    models.Q(
                        ("academic_unit__isnull", False),
                        ("scope_type", "institution"),
                        ("target_type", "academic_unit"),
                    ),
                    _connector="OR",
                ),
                name="libraries_library_target_type_valid",
                violation_error_message="Utility libraries cannot have an academic unit; academic unit libraries must specify an academic unit and belong to an institution.",
            ),
        ),
    ]
