# Generated by Django 6.0.8 on 2026-08-23 09:50

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("libraries", "0001_initial"),
        ("resources", "0001_initial"),
    ]

    operations = [
        CreateExtension("vector"),
        migrations.CreateModel(
            name="ProcessingRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("extract", "Extract"),
                            ("normalize", "Normalize"),
                            ("chunk", "Chunk"),
                            ("embed", "Embed"),
                            ("index", "Index"),
                            ("finalize", "Finalize"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "source_checksum",
                    models.CharField(
                        help_text="SHA-256 hex digest of the resource content at run creation.",
                        max_length=64,
                    ),
                ),
                (
                    "pipeline_version",
                    models.CharField(
                        default="1",
                        help_text="Version of normalization and orchestration pipeline.",
                        max_length=50,
                    ),
                ),
                (
                    "extractor_version",
                    models.CharField(
                        help_text="Version of format-specific extractor module.",
                        max_length=50,
                    ),
                ),
                (
                    "chunker_version",
                    models.CharField(
                        default="1",
                        help_text="Version and configuration of chunking parameters.",
                        max_length=50,
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        help_text="Provider model identifier (e.g. text-embedding-3-small).",
                        max_length=100,
                    ),
                ),
                (
                    "embedding_version",
                    models.CharField(
                        default="1",
                        help_text="Generation/version of embeddings for this model.",
                        max_length=50,
                    ),
                ),
                (
                    "embedding_dimensions",
                    models.PositiveIntegerField(
                        help_text="Dimension of embedding vectors produced by provider."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if this is the active searchable processing run for the resource.",
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery task correlation ID for observability.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of execution attempts."
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        help_text="Machine-readable failure code.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Human-readable error details.", null=True
                    ),
                ),
                (
                    "queued_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_runs",
                        to="libraries.library",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_runs",
                        to="resources.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "processing run",
                "verbose_name_plural": "processing runs",
                "db_table": "processing_run",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text="Zero-based sequence order within the processing run."
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Canonical normalized text content of the chunk."
                    ),
                ),
                (
                    "token_count",
                    models.PositiveIntegerField(
                        help_text="Estimated token count for budgeting."
                    ),
                ),
                (
                    "char_start",
                    models.PositiveIntegerField(
                        help_text="Start offset in the full normalized text."
                    ),
                ),
                (
                    "char_end",
                    models.PositiveIntegerField(
                        help_text="End offset in the full normalized text."
                    ),
                ),
                (
                    "page_start",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="First page number (1-indexed) containing this chunk.",
                        null=True,
                    ),
                ),
                (
                    "page_end",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Last page number (1-indexed) containing this chunk.",
                        null=True,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="Nearest preceding section heading path.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "content_sha256",
                    models.CharField(
                        help_text="SHA-256 hex digest of the chunk text.", max_length=64
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_chunks",
                        to="libraries.library",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_chunks",
                        to="resources.resource",
                    ),
                ),
                (
                    "processing_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="processing.processingrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "document chunk",
                "verbose_name_plural": "document chunks",
                "db_table": "document_chunk",
                "ordering": ["processing_run", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="ChunkEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vector",
                    pgvector.django.vector.VectorField(
                        dimensions=1536,
                        help_text="Dense vector representation (1536 dims for MVP).",
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        db_index=True,
                        help_text="Model identifier used to produce the vector.",
                        max_length=100,
                    ),
                ),
                (
                    "embedding_version",
                    models.CharField(
                        db_index=True,
                        default="1",
                        help_text="Generation/version of embeddings for this model.",
                        max_length=50,
                    ),
                ),
                (
                    "dimensions",
                    models.PositiveIntegerField(
                        help_text="Dimension of the vector as reported by the provider."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="processing.documentchunk",
                    ),
                ),
            ],
            options={
                "verbose_name": "chunk embedding",
                "verbose_name_plural": "chunk embeddings",
                "db_table": "chunk_embedding",
                "ordering": ["-created_at"],
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["vector"],
                        m=16,
                        name="chunk_embedding_vector_hnsw",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chunk", "embedding_model", "embedding_version"),
                        name="chunk_embedding_identity_unique",
                        violation_error_message="An embedding for this chunk, model, and version already exists.",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="processingrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "failed"), _negated=True),
                fields=(
                    "resource",
                    "source_checksum",
                    "pipeline_version",
                    "extractor_version",
                    "chunker_version",
                    "embedding_model",
                    "embedding_version",
                ),
                name="processing_run_identity_non_failed_unique",
                violation_error_message="A non-failed processing run with identical identity already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="processingrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("resource",),
                name="processing_run_active_unique",
                violation_error_message="Only one processing run can be active per resource.",
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["library", "resource"], name="document_ch_library_74754b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["processing_run", "sequence"],
                name="document_ch_process_cb1fe6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentchunk",
            constraint=models.UniqueConstraint(
                fields=("processing_run", "sequence"),
                name="document_chunk_run_sequence_unique",
                violation_error_message="Chunk sequence must be unique per processing run.",
            ),
        ),
    ]
