# Generated by Django 6.0.8 on 2026-09-02 14:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0002_library_personal_scope"),
        ("processing", "0001_initial"),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentStructureNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("part", "Part"),
                            ("chapter", "Chapter"),
                            ("section", "Section"),
                            ("subsection", "Subsection"),
                            ("appendix", "Appendix"),
                            ("front_matter", "Front Matter"),
                            ("back_matter", "Back Matter"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="1-based hierarchy depth level (1=top/root level).",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Original title/heading of this structural node.",
                        max_length=500,
                    ),
                ),
                (
                    "normalized_title",
                    models.CharField(
                        help_text="Canonical normalized title.", max_length=500
                    ),
                ),
                (
                    "page_start",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="First page number (1-indexed) containing this structural node.",
                        null=True,
                    ),
                ),
                (
                    "page_end",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Last page number (1-indexed) containing this structural node.",
                        null=True,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text="Zero-based sequence order within the processing run."
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="native",
                        help_text="Source of hierarchy detection (e.g. native, heading_style).",
                        max_length=50,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Confidence score (0.0 to 1.0) if node was inferred.",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary structural metadata (e.g. outline destination details).",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structure_nodes",
                        to="libraries.library",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="processing.documentstructurenode",
                    ),
                ),
                (
                    "processing_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structure_nodes",
                        to="processing.processingrun",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structure_nodes",
                        to="resources.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "document structure node",
                "verbose_name_plural": "document structure nodes",
                "db_table": "document_structure_node",
                "ordering": ["processing_run", "sequence"],
            },
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="structure_node",
            field=models.ForeignKey(
                blank=True,
                help_text="Deepest enclosing structural node for this chunk.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chunks",
                to="processing.documentstructurenode",
            ),
        ),
        migrations.AddIndex(
            model_name="documentstructurenode",
            index=models.Index(
                fields=["processing_run", "parent"],
                name="document_st_process_61179d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentstructurenode",
            index=models.Index(
                fields=["resource", "page_start", "page_end"],
                name="document_st_resourc_e436d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentstructurenode",
            index=models.Index(
                fields=["library", "resource"], name="document_st_library_224826_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentstructurenode",
            constraint=models.UniqueConstraint(
                fields=("processing_run", "sequence"),
                name="document_structure_node_run_seq_unique",
                violation_error_message="Structure node sequence must be unique per processing run.",
            ),
        ),
    ]
