# Generated by Django 6.0.8 on 2026-09-02 19:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "processing",
            "0002_documentstructurenode_documentchunk_structure_node_and_more",
        ),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookIndexEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        help_text="Original index term text (e.g. 'chemical kinetics').",
                        max_length=255,
                    ),
                ),
                (
                    "normalized_term",
                    models.CharField(
                        db_index=True,
                        help_text="Canonical normalized term for case/punctuation-insensitive lookup.",
                        max_length=255,
                    ),
                ),
                (
                    "subterm",
                    models.CharField(
                        blank=True,
                        help_text="Optional subentry specification (e.g. 'temperature effects').",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "raw_page_references",
                    models.CharField(
                        help_text="Raw extracted page reference string (e.g. '6, 27, 103-105').",
                        max_length=255,
                    ),
                ),
                (
                    "target_physical_pages",
                    models.JSONField(
                        default=list,
                        help_text="List of resolved 1-based physical page numbers.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "processing_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="index_entries",
                        to="processing.processingrun",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="index_entries",
                        to="resources.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "book index entry",
                "verbose_name_plural": "book index entries",
                "db_table": "book_index_entry",
                "ordering": ["processing_run", "normalized_term"],
                "indexes": [
                    models.Index(
                        fields=["resource", "normalized_term"],
                        name="book_index__resourc_42a243_idx",
                    ),
                    models.Index(
                        fields=["processing_run", "normalized_term"],
                        name="book_index__process_e1d1ce_idx",
                    ),
                ],
            },
        ),
    ]
