# Generated by Django 6.0.8 on 2026-09-03 06:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0003_bookindexentry"),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentPageMap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "physical_page",
                    models.PositiveIntegerField(
                        help_text="1-based physical document page number."
                    ),
                ),
                (
                    "printed_label",
                    models.CharField(
                        db_index=True,
                        help_text="Printed page label (e.g. '1', 'iv', 'A-1', 'cover').",
                        max_length=50,
                    ),
                ),
                (
                    "normalized_label",
                    models.CharField(
                        db_index=True,
                        help_text="Normalized page label for case/punctuation-insensitive lookup.",
                        max_length=50,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("native", "Native PDF /PageLabels"),
                            ("detected", "Header/Footer Inferred"),
                            ("default", "Default 1:1 Physical"),
                        ],
                        default="default",
                        help_text="Source of page mapping.",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "processing_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_maps",
                        to="processing.processingrun",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_maps",
                        to="resources.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "document page map",
                "verbose_name_plural": "document page maps",
                "db_table": "document_page_map",
                "ordering": ["processing_run", "physical_page"],
                "indexes": [
                    models.Index(
                        fields=["resource", "normalized_label"],
                        name="document_pa_resourc_0aa0f7_idx",
                    ),
                    models.Index(
                        fields=["processing_run", "normalized_label"],
                        name="document_pa_process_659e21_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("processing_run", "physical_page"),
                        name="document_page_map_run_physical_unique",
                        violation_error_message="Physical page must be unique per processing run.",
                    )
                ],
            },
        ),
    ]
