# Generated by Django 6.0.8 on 2026-08-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("suspended", "Suspended"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
    ]
