# Generated by Django 6.0.8 on 2026-09-04 23:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0005_alter_institutionalauditevent_action_academicunit"),
        ("memberships", "0003_alter_membership_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="academic_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="The academic unit (e.g. class/grade) this student is placed in.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_memberships",
                to="institutions.academicunit",
            ),
        ),
        migrations.CreateModel(
            name="TeachingAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional subject taught (e.g. Mathematics, Science).",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_assignments",
                        to="institutions.academicunit",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_assignments",
                        to="institutions.institution",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_assignments",
                        to="memberships.membership",
                    ),
                ),
            ],
            options={
                "verbose_name": "teaching assignment",
                "verbose_name_plural": "teaching assignments",
                "db_table": "memberships_teachingassignment",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["institution", "status"],
                        name="memberships_institu_e6db52_idx",
                    ),
                    models.Index(
                        fields=["academic_unit", "status"],
                        name="memberships_academi_0183d5_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("membership", "academic_unit", "subject"),
                        name="memberships_teachingassignment_unique_active",
                        violation_error_message="An active teaching assignment for this teacher, academic unit, and subject already exists.",
                    )
                ],
            },
        ),
    ]
