# Generated by Django 6.0.8 on 2026-08-24 09:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("libraries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Connector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "connector_type",
                    models.CharField(
                        choices=[
                            ("web_crawler", "Web Crawler"),
                            ("google_drive", "Google Drive"),
                            ("notion", "Notion"),
                            ("s3", "Amazon S3"),
                            ("file_system", "File System"),
                            ("custom", "Custom Adapter"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("none", "No Authentication"),
                            ("api_key", "API Key"),
                            ("oauth2", "OAuth 2.0"),
                            ("basic_auth", "Basic Auth"),
                            ("bearer_token", "Bearer Token"),
                        ],
                        default="none",
                        max_length=50,
                    ),
                ),
                (
                    "config_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON Schema defining connection-level configuration requirements.",
                    ),
                ),
                (
                    "auth_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON Schema defining required authentication credentials.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this connector is available for new library connections.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "connector",
                "verbose_name_plural": "connectors",
                "db_table": "connectors_connector",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["connector_type", "is_active"],
                        name="connectors__connect_8f684a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                            ("syncing", "Syncing"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Connection-specific settings conforming to Connector.config_schema.",
                    ),
                ),
                (
                    "encrypted_credentials",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Encrypted credentials payload.",
                    ),
                ),
                (
                    "sync_frequency",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_sync_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial Success"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("last_sync_error", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="libraries.library",
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="connections",
                        to="connectors.connector",
                    ),
                ),
            ],
            options={
                "verbose_name": "connection",
                "verbose_name_plural": "connections",
                "db_table": "connectors_connection",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConnectionSyncJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery correlation task ID.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "resources_discovered",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Count of remote resources discovered during sync.",
                    ),
                ),
                (
                    "resources_created",
                    models.PositiveIntegerField(
                        default=0, help_text="Count of new resources imported."
                    ),
                ),
                (
                    "resources_updated",
                    models.PositiveIntegerField(
                        default=0, help_text="Count of existing resources updated."
                    ),
                ),
                (
                    "resources_deleted",
                    models.PositiveIntegerField(
                        default=0, help_text="Count of stale resources removed."
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=100, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_jobs",
                        to="connectors.connection",
                    ),
                ),
            ],
            options={
                "verbose_name": "connection sync job",
                "verbose_name_plural": "connection sync jobs",
                "db_table": "connectors_sync_job",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["connection", "-created_at"],
                        name="connectors__connect_e6f0d4_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="connectors__status_d0b883_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["library", "-created_at"], name="connectors__library_ac2ef6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["connector", "status"], name="connectors__connect_670fba_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="connection",
            constraint=models.UniqueConstraint(
                fields=("library", "name"),
                name="connectors_connection_library_name_unique",
                violation_error_message="A connection with this name already exists in this library.",
            ),
        ),
    ]
