# Generated by Django 6.0.8 on 2026-08-24 00:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContextDomain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "context domain",
                "verbose_name_plural": "context domains",
                "db_table": "context_domain",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GeographicUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("country", "Country"),
                            ("region", "Region"),
                            ("district", "District"),
                            ("county", "County"),
                            ("subcounty", "Subcounty"),
                            ("parish", "Parish"),
                            ("village", "Village"),
                            ("city", "City"),
                            ("town", "Town"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="district",
                        max_length=30,
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="ISO 3166-1 alpha-2 code e.g. UG.",
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary geographic metadata (e.g. alternate names, coordinates).",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="context.geographicunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "geographic unit",
                "verbose_name_plural": "geographic units",
                "db_table": "context_geographic_unit",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContextResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content",
                    models.TextField(
                        help_text="Concise educational contextual knowledge snippet (max 5000 chars).",
                        max_length=5000,
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("platform", "Platform Canonical"),
                            ("institution", "Institution Custom"),
                        ],
                        db_index=True,
                        default="platform",
                        max_length=20,
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Citation or provenance reference.",
                        max_length=512,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "applicable_subjects",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of school subjects (e.g. ['biology', 'agriculture']).",
                    ),
                ),
                (
                    "applicable_topics",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of curriculum topics (e.g. ['photosynthesis', 'crop farming']).",
                    ),
                ),
                (
                    "pedagogical_purposes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of pedagogical purposes (e.g. ['example', 'explanation']).",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "context_domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="context_resources",
                        to="context.contextdomain",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        help_text="Populated when scope_type is INSTITUTION.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_resources",
                        to="institutions.institution",
                    ),
                ),
                (
                    "geographic_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="context_resources",
                        to="context.geographicunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "context resource",
                "verbose_name_plural": "context resources",
                "db_table": "context_resource",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InstitutionContextRegion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Priority rank: 1 is highest priority focus region.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "geographic_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution_context_regions",
                        to="context.geographicunit",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_regions",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "institution context region",
                "verbose_name_plural": "institution context regions",
                "db_table": "context_institution_region",
                "ordering": ["priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserFamiliarRegion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Priority rank: 1 is highest priority familiarity.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "geographic_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_familiar_regions",
                        to="context.geographicunit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="familiar_regions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user familiar region",
                "verbose_name_plural": "user familiar regions",
                "db_table": "context_user_familiar_region",
                "ordering": ["priority", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="geographicunit",
            constraint=models.UniqueConstraint(
                fields=("parent", "slug"),
                name="context_geounit_parent_slug_unique",
                violation_error_message="A geographic unit with this slug already exists under this parent.",
            ),
        ),
        migrations.AddConstraint(
            model_name="geographicunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("slug",),
                name="context_geounit_root_slug_unique",
                violation_error_message="A root geographic unit with this slug already exists.",
            ),
        ),
        migrations.AddIndex(
            model_name="contextresource",
            index=models.Index(
                fields=["geographic_unit", "status"],
                name="context_res_geograp_628851_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contextresource",
            index=models.Index(
                fields=["context_domain", "status"],
                name="context_res_context_c300e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contextresource",
            index=models.Index(
                fields=["scope_type", "institution"],
                name="context_res_scope_t_48ffd3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="contextresource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("scope_type", "platform"), ("institution__isnull", True)),
                    models.Q(
                        ("scope_type", "institution"), ("institution__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="context_resource_scope_institution_integrity",
                violation_error_message="Platform resources must not specify an institution; Institution resources must specify an institution.",
            ),
        ),
        migrations.AddConstraint(
            model_name="institutioncontextregion",
            constraint=models.UniqueConstraint(
                fields=("institution", "geographic_unit"),
                name="context_inst_region_unit_unique",
                violation_error_message="This geographic unit is already configured for this institution.",
            ),
        ),
        migrations.AddConstraint(
            model_name="userfamiliarregion",
            constraint=models.UniqueConstraint(
                fields=("user", "geographic_unit"),
                name="context_user_familiar_unit_unique",
                violation_error_message="This geographic unit is already configured in your familiar regions.",
            ),
        ),
    ]
