# Generated by Django 6.0.8 on 2026-08-29 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="contextresource",
            name="applicable_topics",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of curriculum topics (e.g. ['photosynthesis']).",
            ),
        ),
        migrations.AlterConstraint(
            model_name="userfamiliarregion",
            name="context_user_familiar_unit_unique",
            constraint=models.UniqueConstraint(
                fields=("user", "geographic_unit"),
                name="context_user_familiar_unit_unique",
                violation_error_message="This geographic unit is already in your familiar regions.",
            ),
        ),
    ]
