# Generated by Django 6.0.8 on 2026-08-23 16:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutions", "0001_initial"),
        ("libraries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary session configuration and preferences.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_sessions",
                        to="institutions.institution",
                    ),
                ),
                (
                    "primary_library",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_sessions",
                        to="libraries.library",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "agent session",
                "verbose_name_plural": "agent sessions",
                "db_table": "agents_session",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentRunRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(help_text="User prompt that initiated this run."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("awaiting_input", "Awaiting Input"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("timed_out", "Timed Out"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "answer",
                    models.TextField(
                        blank=True,
                        help_text="Final synthesized answer from the agent.",
                        null=True,
                    ),
                ),
                (
                    "citations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of 14-field citation evidence objects.",
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        help_text="Machine-readable failure code.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Human-readable error details.", null=True
                    ),
                ),
                (
                    "step_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of reasoning steps executed."
                    ),
                ),
                (
                    "prompt_tokens",
                    models.PositiveIntegerField(
                        default=0, help_text="Total prompt tokens consumed."
                    ),
                ),
                (
                    "completion_tokens",
                    models.PositiveIntegerField(
                        default=0, help_text="Total completion tokens consumed."
                    ),
                ),
                (
                    "total_tokens",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total tokens consumed (prompt + completion).",
                    ),
                ),
                (
                    "timeout_seconds",
                    models.FloatField(
                        default=60.0,
                        help_text="Maximum execution time budget in seconds.",
                    ),
                ),
                (
                    "max_steps",
                    models.PositiveIntegerField(
                        default=10, help_text="Maximum reasoning steps allowed."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "queued_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When the run entered the dispatch queue.",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When execution actually began in the Agent Service.",
                        null=True,
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the run reached a terminal status.",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="agents.agentsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "agent run record",
                "verbose_name_plural": "agent run records",
                "db_table": "agents_run_record",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentSessionMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Message text content.")),
                (
                    "citations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Citation evidence attached to this message.",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text="Zero-based ordering position within the session transcript."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        help_text="The agent run that produced this message, if applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="agents.agentrunrecord",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="agents.agentsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "agent session message",
                "verbose_name_plural": "agent session messages",
                "db_table": "agents_session_message",
                "ordering": ["session", "sequence"],
            },
        ),
        migrations.AddIndex(
            model_name="agentsession",
            index=models.Index(
                fields=["user", "-updated_at"], name="agents_sess_user_id_f4a1a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentsession",
            index=models.Index(
                fields=["institution", "-updated_at"],
                name="agents_sess_institu_71a58c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentrunrecord",
            index=models.Index(
                fields=["session", "-created_at"], name="agents_run__session_087a11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrunrecord",
            index=models.Index(
                fields=["user", "-created_at"], name="agents_run__user_id_2a8a9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrunrecord",
            index=models.Index(
                fields=["status", "queued_at"], name="agents_run__status_c61fdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrunrecord",
            index=models.Index(
                fields=["status", "started_at"], name="agents_run__status_918ae7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentsessionmessage",
            constraint=models.UniqueConstraint(
                fields=("session", "sequence"),
                name="agents_message_session_sequence_unique",
                violation_error_message="A message with this sequence number already exists in the session.",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentsessionmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "assistant"), ("run__isnull", False)),
                fields=("run",),
                name="agents_message_one_assistant_per_run_unique",
                violation_error_message="Only one assistant message is allowed per agent run.",
            ),
        ),
    ]
