# Generated by Django 6.0.8 on 2026-08-24 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentsession",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                help_text="The institution context for this session. Null for memberless users who only have access to platform/public knowledge.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_sessions",
                to="institutions.institution",
            ),
        ),
    ]
