# Generated by Django for Phase 2 Institutional Console

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="institution_type",
            field=models.CharField(
                choices=[
                    ("family", "Family"),
                    ("school", "School (K-12)"),
                    ("college", "College / Vocational Institute"),
                    ("university", "University / Higher Education"),
                    ("training_center", "Training Center / Academy"),
                    ("education_organization", "Educational Organization / NGO"),
                    ("other", "Other Organization"),
                ],
                db_index=True,
                default="school",
                help_text="The organizational classification of this learning workspace.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who originally established this institution workspace.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_institutions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
