# Generated by Django 6.0.8 on 2026-09-03 12:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0002_institution_type_and_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionalAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("member.role_changed", "Member Role Changed"),
                            ("member.status_changed", "Member Status Changed"),
                            ("member.removed", "Member Removed"),
                            ("library.created", "Library Created"),
                            ("library.updated", "Library Updated"),
                            ("library.deleted", "Library Deleted"),
                            ("access.granted", "Access Policy Granted"),
                            ("access.updated", "Access Policy Updated"),
                            ("access.revoked", "Access Policy Revoked"),
                            ("resource.uploaded", "Resource Uploaded"),
                            ("resource.deleted", "Resource Deleted"),
                            ("resource.reindexed", "Resource Reindexed"),
                            ("connection.created", "Connection Created"),
                            ("connection.updated", "Connection Updated"),
                            ("connection.deleted", "Connection Deleted"),
                            ("connection.sync_triggered", "Sync Triggered"),
                            ("institution.updated", "Institution Settings Updated"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("target_type", models.CharField(db_index=True, max_length=50)),
                ("target_id", models.CharField(blank=True, default="", max_length=255)),
                ("target_repr", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "institutional audit event",
                "verbose_name_plural": "institutional audit events",
                "db_table": "institutions_audit_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["institution", "-created_at"],
                        name="institution_institu_d81fea_idx",
                    ),
                    models.Index(
                        fields=["institution", "action"],
                        name="institution_institu_71fdc5_idx",
                    ),
                ],
            },
        ),
    ]
