# Generated by Django 6.0.8 on 2026-09-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0003_institutionalauditevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="logo_content_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="MIME content type of the stored logo (e.g. image/png).",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="logo_object_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Object storage key for the institutional badge/logo.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="logo_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the branding logo was last modified.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="institutionalauditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("member.role_changed", "Member Role Changed"),
                    ("member.status_changed", "Member Status Changed"),
                    ("member.removed", "Member Removed"),
                    ("library.created", "Library Created"),
                    ("library.updated", "Library Updated"),
                    ("library.deleted", "Library Deleted"),
                    ("library.invitation_created", "Library Invitation Created"),
                    ("library.invitation_revoked", "Library Invitation Revoked"),
                    ("library.invitation_accepted", "Library Invitation Accepted"),
                    ("library.invitation_declined", "Library Invitation Declined"),
                    ("access.granted", "Access Policy Granted"),
                    ("access.updated", "Access Policy Updated"),
                    ("access.revoked", "Access Policy Revoked"),
                    ("resource.uploaded", "Resource Uploaded"),
                    ("resource.deleted", "Resource Deleted"),
                    ("resource.reindexed", "Resource Reindexed"),
                    ("connection.created", "Connection Created"),
                    ("connection.updated", "Connection Updated"),
                    ("connection.deleted", "Connection Deleted"),
                    ("connection.sync_triggered", "Sync Triggered"),
                    ("institution.updated", "Institution Settings Updated"),
                    ("institution.branding_updated", "Branding Updated"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
