# Generated by Django 6.0.8 on 2026-09-04 23:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0004_institution_logo_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutionalauditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("member.role_changed", "Member Role Changed"),
                    ("member.status_changed", "Member Status Changed"),
                    ("member.removed", "Member Removed"),
                    ("library.created", "Library Created"),
                    ("library.updated", "Library Updated"),
                    ("library.deleted", "Library Deleted"),
                    ("library.invitation_created", "Library Invitation Created"),
                    ("library.invitation_revoked", "Library Invitation Revoked"),
                    ("library.invitation_accepted", "Library Invitation Accepted"),
                    ("library.invitation_declined", "Library Invitation Declined"),
                    ("access.granted", "Access Policy Granted"),
                    ("access.updated", "Access Policy Updated"),
                    ("access.revoked", "Access Policy Revoked"),
                    ("resource.uploaded", "Resource Uploaded"),
                    ("resource.deleted", "Resource Deleted"),
                    ("resource.reindexed", "Resource Reindexed"),
                    ("connection.created", "Connection Created"),
                    ("connection.updated", "Connection Updated"),
                    ("connection.deleted", "Connection Deleted"),
                    ("connection.sync_triggered", "Sync Triggered"),
                    ("institution.updated", "Institution Settings Updated"),
                    ("institution.branding_updated", "Branding Updated"),
                    ("academic_unit.created", "Academic Unit Created"),
                    ("academic_unit.updated", "Academic Unit Updated"),
                    ("academic_unit.deactivated", "Academic Unit Deactivated"),
                    ("academic_unit.deleted", "Academic Unit Deleted"),
                    ("student.placed", "Student Placed in Academic Unit"),
                    ("student.unassigned", "Student Academic Unit Unassigned"),
                    ("teacher.assigned", "Teacher Assigned to Academic Unit"),
                    ("teacher.unassigned", "Teacher Removed from Academic Unit"),
                    ("library.targeting_updated", "Library Targeting Updated"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="AcademicUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(db_index=True, max_length=50)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("grade", "Grade Level"),
                            ("year", "Year / Form"),
                            ("department", "Department"),
                            ("stream", "Stream / Class Section"),
                            ("stage", "Stage / Level"),
                            ("other", "Other Unit"),
                        ],
                        db_index=True,
                        default="grade",
                        max_length=30,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Sequence index for academic progression (e.g. 1 for P1, 2 for P2).",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_units",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "academic unit",
                "verbose_name_plural": "academic units",
                "db_table": "institutions_academicunit",
                "ordering": ["order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("institution", "code"),
                        name="institutions_academicunit_institution_code_unique",
                        violation_error_message="An active academic unit with this code already exists in this institution.",
                    )
                ],
            },
        ),
    ]
