# Generated by Django 6.0.8 on 2026-08-25 01:30

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User's public/chosen display name.",
                        max_length=150,
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL pointing to the user's avatar image.",
                        max_length=500,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional contact phone number.",
                        max_length=30,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Short biographical summary or teaching/learning focus.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user profile",
                "verbose_name_plural": "user profiles",
                "db_table": "users_profile",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pedagogical_style",
                    models.CharField(
                        choices=[
                            ("intuitive", "Intuitive & Analogy-driven"),
                            ("formal", "Formal & Academic"),
                            ("socratic", "Socratic & Inquiring"),
                        ],
                        default="intuitive",
                        help_text="Preferred style for explanations.",
                        max_length=20,
                    ),
                ),
                (
                    "explanation_depth",
                    models.CharField(
                        choices=[
                            ("concise", "Concise Summary"),
                            ("standard", "Standard Explanation"),
                            ("in_depth", "In-depth / Deep Dive"),
                        ],
                        default="standard",
                        help_text="Preferred depth/detail level for explanations.",
                        max_length=20,
                    ),
                ),
                (
                    "response_language",
                    models.CharField(
                        default="en",
                        help_text="Target language for AI explanations (e.g., 'en', 'sw').",
                        max_length=10,
                    ),
                ),
                (
                    "cross_session_memory",
                    models.BooleanField(
                        default=True,
                        help_text="Allow Mwalimu to reference relevant concepts across chat sessions.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user preference",
                "verbose_name_plural": "user preferences",
                "db_table": "users_preference",
                "ordering": ["-created_at"],
            },
        ),
    ]
