# Generated by Django 6.0.8 on 2026-08-29 07:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_profile_and_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="google_sub",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Google OAuth stable subject identifier (sub).",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "otp_hash",
                    models.CharField(
                        help_text="Cryptographic SHA-256 hash of the 6-digit OTP.",
                        max_length=128,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("email_verification", "Email Verification"),
                            ("password_reset", "Password Reset"),
                        ],
                        db_index=True,
                        default="email_verification",
                        max_length=32,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Failed verification attempts (max 5)."
                    ),
                ),
                (
                    "resend_available_at",
                    models.DateTimeField(
                        help_text="Timestamp when next OTP request is allowed (60s cooldown)."
                    ),
                ),
                ("is_used", models.BooleanField(db_index=True, default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "email OTP",
                "verbose_name_plural": "email OTPs",
                "db_table": "users_email_otp",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "purpose", "is_used"],
                        name="users_email_email_068dbd_idx",
                    )
                ],
            },
        ),
    ]
