# Generated by Django 6.0.8 on 2026-09-04 16:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        db_index=True,
                        help_text="Stable identifier e.g. library.invitation or membership.approved",
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured action & deep-link metadata (e.g. invitation_id, library_id).",
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acted_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "db_table": "communications_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="communicati_recipie_fc8f0b_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="communicati_recipie_df41d2_idx",
                    ),
                    models.Index(
                        fields=["recipient", "notification_type"],
                        name="communicati_recipie_512e0f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboxMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("auth.email_verification", "Email Verification OTP"),
                            ("auth.password_reset", "Password Reset OTP"),
                            ("auth.welcome", "Welcome New User"),
                            (
                                "library.invitation.existing_user",
                                "Library Invitation (Existing User)",
                            ),
                            (
                                "library.invitation.new_user",
                                "Library Invitation (New User)",
                            ),
                            (
                                "library.invitation.accepted",
                                "Library Invitation Accepted",
                            ),
                            (
                                "library.invitation.declined",
                                "Library Invitation Declined",
                            ),
                            (
                                "library.invitation.revoked",
                                "Library Invitation Revoked",
                            ),
                            ("membership.requested", "Membership Requested"),
                            ("membership.approved", "Membership Approved"),
                            ("membership.suspended", "Membership Suspended"),
                            ("membership.role_updated", "Membership Role Updated"),
                            ("system.announcement", "System Announcement"),
                            ("security.alert", "Security Alert"),
                        ],
                        db_index=True,
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("authentication", "Authentication"),
                            ("account", "Account"),
                            ("institution", "Institution"),
                            ("membership", "Membership"),
                            ("library", "Library"),
                            ("system", "System"),
                            ("security", "Security"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("recipient_email", models.EmailField(db_index=True, max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("html_body", models.TextField()),
                ("text_body", models.TextField(blank=True, default="")),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("retrying", "Retrying"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "external_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbox_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "outbox message",
                "verbose_name_plural": "outbox messages",
                "db_table": "communications_outbox_message",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="communicati_status_356989_idx",
                    ),
                    models.Index(
                        fields=["recipient_email", "-created_at"],
                        name="communicati_recipie_97db07_idx",
                    ),
                ],
            },
        ),
    ]
